pull_request_rules:
    - name: Automatic merge on approval
      conditions:
        - "#approved-reviews-by>=1"
      actions:
        merge:
          method: merge

    - name: automatic merge for ImgBot pull requests
      conditions:
        - author=imgbot[bot]
        - status-success=Travis CI - Pull Request
      actions:
      merge:
        method: merge
    
    - name: ask to resolve conflict
      conditions:
        - conflict
      actions:
        comment:
          message: This pull request is now in conflicts. Could you fix it @{{author}}? 🙏
    
    - name: delete head branch after merge
      conditions:
        - merged
      actions:
        delete_head_branch: {}
