# Jekyll site
# Build the Jekyll site with the GitHub Pages gem on Ubuntu agents.
# Add steps that build, test, save build artifacts, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseRubyVersion@0
  displayName: 'Select Ruby version'
  inputs:
    bundle config set --local path 'vendor/bundle'
    bundle install --jobs 4 --retry 3
  displayName: 'Install Ruby gems'

- script: |
    bundle exec jekyll build --future
    ls -la _site
  displayName: 'Build Jekyll site'
